### ISSUE TITLE
Main Menu UI

### ISSUE THREAD

**Issue by laconc** [laconc/MathQuest#4]
Alter the FXML file so that the screen looks like the wireframe.

Admin Tools should only show up if the account logged in is of type 'admin'.
Options should only show up if the account logged in is of type 'user'.

![Main Menu Wireframe](https://cloud.githubusercontent.com/assets/20423536/19745364/ee8b228a-9b96-11e6-9106-0ad7830ac279.png)

**Comment by laconc** [comment]
> Admin Tools should only show up if the account logged in is of type 'admin'.
> Options should only show up if the account logged in is of type 'user'.

Done!

**Comment by gluckenbach11** [comment]
Minimal changes needed. Resized and rearranged.
