### ISSUE TITLE
Options UI

### ISSUE THREAD

**Issue by laconc** [laconc/MathQuest#5]
1. Create the FXML file.
2. Alter the FXML file so that the screen looks like the wireframe.

![Options Wireframe](https://cloud.githubusercontent.com/assets/20423536/19745227/6de281dc-9b96-11e6-85e1-45b0c92743a3.png)

**Comment by laconc** [comment]
File was created but the controls need to be positioned.

**Comment by gluckenbach11** [comment]
Minimal changes needed. Minor alignment issues and button sizing.
