### ISSUE TITLE
Game UI

### ISSUE THREAD

**Issue by laconc** [laconc/MathQuest#6]
1. Create the FXML file.
2. Alter the FXML file so that the screen looks like the wireframe.

![Game Wireframe](https://cloud.githubusercontent.com/assets/20423536/19745401/13664d1e-9b97-11e6-8d4c-be3cffc9eea1.png)

**Comment by gluckenbach11** [comment]
FMXL created and mimics the wireframe needs tied to the actual model classes governing function, seems confusing but likely is less so than I'm making it...
